// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smtp.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RawEmailReceivedEvent struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InboxName            string   `protobuf:"bytes,2,opt,name=inbox_name,json=inboxName,proto3" json:"inbox_name,omitempty"`
	Raw                  []byte   `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawEmailReceivedEvent) Reset()         { *m = RawEmailReceivedEvent{} }
func (m *RawEmailReceivedEvent) String() string { return proto.CompactTextString(m) }
func (*RawEmailReceivedEvent) ProtoMessage()    {}
func (*RawEmailReceivedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40e017a3db57e14, []int{0}
}

func (m *RawEmailReceivedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawEmailReceivedEvent.Unmarshal(m, b)
}
func (m *RawEmailReceivedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawEmailReceivedEvent.Marshal(b, m, deterministic)
}
func (m *RawEmailReceivedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawEmailReceivedEvent.Merge(m, src)
}
func (m *RawEmailReceivedEvent) XXX_Size() int {
	return xxx_messageInfo_RawEmailReceivedEvent.Size(m)
}
func (m *RawEmailReceivedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RawEmailReceivedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RawEmailReceivedEvent proto.InternalMessageInfo

func (m *RawEmailReceivedEvent) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RawEmailReceivedEvent) GetInboxName() string {
	if m != nil {
		return m.InboxName
	}
	return ""
}

func (m *RawEmailReceivedEvent) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

func init() {
	proto.RegisterType((*RawEmailReceivedEvent)(nil), "stmp.RawEmailReceivedEvent")
}

func init() { proto.RegisterFile("smtp.proto", fileDescriptor_b40e017a3db57e14) }

var fileDescriptor_b40e017a3db57e14 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0x8d, 0xb1, 0x0a, 0xc2, 0x30,
	0x18, 0x84, 0xa9, 0x95, 0x4a, 0x83, 0x43, 0x09, 0x88, 0x45, 0x11, 0x8a, 0x53, 0x27, 0x33, 0xf8,
	0x06, 0x42, 0x07, 0x17, 0x87, 0x8c, 0x2e, 0xe5, 0x6f, 0xf3, 0x1b, 0x82, 0x4d, 0x13, 0xd2, 0xb4,
	0xd5, 0xb7, 0x97, 0xc6, 0xed, 0xee, 0xbb, 0x83, 0x8f, 0x90, 0x41, 0x7b, 0x7b, 0xb1, 0xce, 0x78,
	0x43, 0xd7, 0x83, 0xd7, 0xf6, 0x70, 0x94, 0xc6, 0xc8, 0x0e, 0x59, 0x60, 0xcd, 0xf8, 0x62, 0xa8,
	0xad, 0xff, 0xfe, 0x2f, 0x67, 0x20, 0x3b, 0x0e, 0x73, 0xa5, 0x41, 0x75, 0x1c, 0x5b, 0x54, 0x13,
	0x8a, 0x6a, 0xc2, 0xde, 0xd3, 0x3d, 0xd9, 0x8c, 0x03, 0xba, 0x5a, 0x89, 0x3c, 0x2a, 0xa2, 0x32,
	0xe5, 0xc9, 0x52, 0xef, 0x82, 0x9e, 0x08, 0x51, 0x7d, 0x63, 0x3e, 0x75, 0x0f, 0x1a, 0xf3, 0x55,
	0xd8, 0xd2, 0x40, 0x1e, 0xa0, 0x91, 0x66, 0x24, 0x76, 0x30, 0xe7, 0x71, 0x11, 0x95, 0x5b, 0xbe,
	0xc4, 0x1b, 0x7d, 0x66, 0xf6, 0x2d, 0x19, 0x08, 0xb0, 0x1e, 0x1d, 0x93, 0xce, 0xb6, 0x4d, 0x12,
	0xec, 0xd7, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x29, 0x11, 0xd0, 0xae, 0x00, 0x00, 0x00,
}
